### PR TITLE
WIP: initial migration to trust-dns 0.19

### PR DESCRIPTION
**Pull request by drahnr**
Since it's quite a pain having to have a certain version of a nightly toolchain making edits harder than necessary, an attempt to remedy this by upgrading to `turst-dns*>= 0.19` and stabilized futures.

Ref #5

### CODE REVIEW

**Comment by valeriansaliou** [comment]
Thanks @drahnr ; this was on my ToDo, but you did it! I'll review the code & test it, then merge it over the evening.

**Comment by drahnr** [comment]
Slow down, things are really very much in progress and this doesn't even compile just yet (hence the draft state of this PR), this will be a slow step by step progress :) feel free to chime in.

First I wanted to move things to be compiling, possibly leaving a few `// TODO FIXME XXX` comments where more work is needed.

Once it compiles, it might make sense to consider moving away from rocket towards something that is entirely futures based to avoid the mixins and the ever-chaning nightly requirement - but that is to be discussed after this migration is complete.

**Comment by valeriansaliou** [comment]
Oh, okay, sorry, I didn't test the code, just quick read changes, so my guess was it was ready to review :)

Let me know then when you feel that it's ready to merge. Thanks again.

**Comment by valeriansaliou** [comment]
References #19 as well, addresses main thread blocking DOS attacks we experienced at Crisp. For now, main thread blocking issue addressed in #20 though this MR will properly fix it for good.

**Comment by paulocoghi** [comment]
Considering that this PR is still in draft, what do you think about updating it with `trust-dns` (now `hickory-dns`) to its latest version `0.24.1`?

**Comment by drahnr** [comment]
> Considering that this PR is still in draft, what do you think about updating it with `trust-dns` (now `hickory-dns`) to its latest version `0.24.1`?

It's been way too long and I won't have time in the foreseeable to work on it. Feel free to pick it up :)

Closing

**Comment by paulocoghi** [comment]
@drahnr that's sad, but thanks anyway for the feedback :smile:

**Comment by drahnr** [comment]
I mean, 4 years, that's ancient history in open source terms by now .

**Comment by valeriansaliou** [comment]
I've started migration work to trust-dns 0.23 (then, I'll move it to the rebranded package), tracked in PR #27

**Pull request closed without merging**
